
services:

  frontend:
    build:
      context: ./frontend/cme_fullstack
      dockerfile: ../Dockerfile
    container_name: cme_frontend
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend_cme
    volumes:
      - ./backend:/backend      
    ports:
      - "8000:8000"
    env_file:
      - ./backend/dotenv_files/.env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres_cme
    environment:
      POSTGRES_DB: cme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cme12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
