# Generated by Django 5.2 on 2025-04-25 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_desc', models.CharField(max_length=200)),
                ('permission1', models.BooleanField(default=False)),
                ('permission2', models.BooleanField(default=False)),
                ('permission3', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='cme_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_serial', models.CharField(blank=True, max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials_products', to='cme_api.product')),
            ],
            options={
                'verbose_name': 'Serial do Produto',
                'verbose_name_plural': 'Seriais dos Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('sector', models.CharField(default='NO DISTRIBUTION', max_length=50)),
                ('produto_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_distribution', to='cme_api.productserial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_distribution', to='cme_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('produto_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_receiving', to='cme_api.productserial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving', to='cme_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_group', to='cme_api.usergroup'),
        ),
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='WASHING', max_length=50)),
                ('produto_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_washing', to='cme_api.productserial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_washing', to='cme_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('RECEIVING', 'Receiving'), ('DISTRIBUTION', 'Distribution'), ('NO WASHING', 'No Washing'), ('WASHING', 'Washing'), ('DISCARDED', 'Discarded')], default='NO PROCESS', max_length=50)),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_process_history', to='cme_api.distribution')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_process_history', to='cme_api.productserial')),
                ('receiving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_process_history', to='cme_api.receiving')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_process_history', to='cme_api.user')),
                ('washing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washing_process_history', to='cme_api.washing')),
            ],
        ),
    ]
