# Generated by Django 5.2 on 2025-04-30 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='cme_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_serial', models.CharField(blank=True, max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NO PROCESS', 'Sem processo'), ('RECEIVING', 'Recebido'), ('WASHING', 'Lavagem'), ('WASHING COMPLETE', 'Lavado'), ('ESTERELIZATION', 'Esterilização'), ('ESTERELIZATION COMPLETE', 'Esterilizado'), ('DISTRIBUTION', 'Distribuído')], default='NO PROCESS', max_length=30)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials_products', to='cme_api.product')),
            ],
            options={
                'verbose_name': 'Serial do Produto',
                'verbose_name_plural': 'Seriais dos Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Esterelization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('isEsterelization', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_esterelization', to=settings.AUTH_USER_MODEL)),
                ('produto_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_esterelization', to='cme_api.productserial')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('sector', models.CharField(default='NO DISTRIBUTION', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_distribution', to=settings.AUTH_USER_MODEL)),
                ('produto_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_distribution', to='cme_api.productserial')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('produto_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_receiving', to='cme_api.productserial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('isWashed', models.BooleanField(default=False)),
                ('produto_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_washing', to='cme_api.productserial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_washing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('RECEIVING', 'Recebimento'), ('DISTRIBUTION', 'Distribuição'), ('WASHING', 'Lavagem Iniciada'), ('WASHING COMPLETE', 'Lavagem Concluída'), ('ESTERELIZATION', 'Esterilização Iniciada'), ('ESTERELIZATION COMPLETE', 'Esterilização Concluída')], default='NO PROCESS', max_length=50)),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_process_history', to='cme_api.distribution')),
                ('esterelization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esterelization_process_history', to='cme_api.esterelization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_process_history', to=settings.AUTH_USER_MODEL)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_process_history', to='cme_api.productserial')),
                ('receiving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_process_history', to='cme_api.receiving')),
                ('washing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washing_process_history', to='cme_api.washing')),
            ],
        ),
    ]
