# Generated by Django 5.2 on 2025-04-30 17:16

from django.db import migrations

def inserir_dados_iniciais(apps, schema_editor):
    Category = apps.get_model("cme_api", "Category")
    Product = apps.get_model("cme_api", "Product")
    ProductSerial = apps.get_model("cme_api", "ProductSerial")
    Group = apps.get_model('auth', 'Group')
    nomes = ['ADMIN', 'TECNICO', 'ENFERMEIRO']
    for nome in nomes:
        Group.objects.get_or_create(name=nome)
    
    produtos = Product.objects.all()
        
    cirurgico = Category.objects.create(type="Cirúrgico", descricao="Material utilizado em procedimentos cirúrgicos")
    enfermagem = Category.objects.create(type="Enfermagem", descricao="Insumos utilizados por enfermeiros")
    uti = Category.objects.create(type="UTI", descricao="Produtos para uso em Unidade de Terapia Intensiva")
        
    Product.objects.create(nome="Bisturi", category=cirurgico)
    Product.objects.create(nome="Seringa 5ml", category=enfermagem)
    Product.objects.create(nome="Cateter Duplo Lúmen", category=uti)
    
    for produto in produtos:
        prefixo = produto.nome[:4].upper()
        for i in range(1, 4):
            codigo = f"{prefixo}{str(i).zfill(3)}"
            ProductSerial.objects.create(
                produto=produto,
                codigo_serial=codigo,
                status="NO PROCESS"  
            )

def remover_dados_iniciais(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Product = apps.get_model("core", "Product")
    Product.objects.filter(nome__in=["Bisturi", "Seringa 5ml", "Cateter Duplo Lúmen"]).delete()
    Category.objects.filter(type__in=["Cirúrgico", "Enfermagem", "UTI"]).delete()
    ProductSerial = apps.get_model("cme_api", "ProductSerial")
    ProductSerial.objects.filter(codigo_serial__regex=r'^[A-Z]{4}\d{3}$').delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(inserir_dados_iniciais, remover_dados_iniciais),
    ]
