# Generated by Django 5.2 on 2025-04-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productserial',
            name='group_desc',
        ),
        migrations.RemoveField(
            model_name='productserial',
            name='permission1',
        ),
        migrations.RemoveField(
            model_name='productserial',
            name='permission2',
        ),
        migrations.RemoveField(
            model_name='productserial',
            name='permission3',
        ),
    ]
