# Generated by Django 5.2 on 2025-04-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0003_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
