# Generated by Django 5.2 on 2025-04-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0004_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washing',
            name='status',
        ),
        migrations.AddField(
            model_name='washing',
            name='isWashed',
            field=models.BooleanField(default=False),
        ),
    ]
