# Generated by Django 5.2 on 2025-04-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0005_remove_washing_status_washing_iswashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhistory',
            name='etapa',
            field=models.CharField(choices=[('RECEIVING', 'Receiving'), ('DISTRIBUTION', 'Distribution'), ('WASHING', 'Washing'), ('DISCARDED', 'Discarded')], default='NO PROCESS', max_length=50),
        ),
    ]
