# Generated by Django 5.2 on 2025-04-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0006_alter_processhistory_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhistory',
            name='etapa',
            field=models.CharField(choices=[('RECEIVING', 'Receiving'), ('DISTRIBUTION', 'Distribution'), ('WASHING', 'Washing'), ('DISCARDED', 'Discarded'), ('WASHING COMPLETE', 'Washing Completed')], default='NO PROCESS', max_length=50),
        ),
    ]
