# Generated by Django 5.2 on 2025-04-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0007_alter_processhistory_etapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Esterelization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_data', models.DateTimeField(auto_now_add=True)),
                ('isWashed', models.BooleanField(default=False)),
                ('isFail', models.BooleanField(default=False)),
                ('produto_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_esterelization', to='cme_api.productserial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_esterelization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
