# Generated by Django 5.2 on 2025-04-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0008_esterelization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esterelization',
            old_name='isWashed',
            new_name='isEsterelization',
        ),
    ]
