# Generated by Django 5.2 on 2025-04-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0009_rename_iswashed_esterelization_isesterelization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhistory',
            name='etapa',
            field=models.CharField(choices=[('RECEIVING', 'Recebimento'), ('DISTRIBUTION', 'Distribuição'), ('WASHING', 'Lavagem Iniciada'), ('WASHING COMPLETE', 'Lavagem Concluída'), ('ESTERELIZATION', 'Esterilização Iniciada'), ('ESTERELIZATION COMPLETE', 'Esterilização Concluída')], default='NO PROCESS', max_length=50),
        ),
    ]
