# Generated by Django 5.2 on 2025-04-29 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0010_alter_processhistory_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='processhistory',
            name='esterelization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esterelization_process_history', to='cme_api.esterelization'),
        ),
    ]
