# Generated by Django 5.2 on 2025-04-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0011_processhistory_esterelization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esterelization',
            name='isFail',
        ),
    ]
