# Generated by Django 5.2 on 2025-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0012_remove_esterelization_isfail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productserial',
            name='status',
            field=models.CharField(choices=[('NEW', 'Novo'), ('RECEIVED', 'Recebido'), ('WASHING', 'Lavagem'), ('WASHED', 'Lavado'), ('ESTERELIZED', 'Esterilizado'), ('DISTRIBUTED', 'Distribuído'), ('NO_PROCESS', 'Sem processo')], default='NO_PROCESS', max_length=30),
        ),
    ]
