# Generated by Django 5.2 on 2025-04-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme_api', '0013_productserial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productserial',
            name='status',
            field=models.CharField(choices=[('NO PROCESS', 'Sem processo'), ('RECEIVING', 'Recebido'), ('WASHING', 'Lavagem'), ('WASHING COMPLETE', 'Lavado'), ('ESTERELIZATION', 'Esterilização'), ('ESTERELIZATION COMPLETE', 'Esterilizado'), ('DISTRIBUTION', 'Distribuído')], default='NO PROCESS', max_length=30),
        ),
    ]
